// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtqUX40GRNuFzC4qF5KZ6f2HAJzLGkQZ8',
    appId: '1:282874129758:web:b842f09cdbb526b089f3cf',
    messagingSenderId: '282874129758',
    projectId: 'ipssi-flutter-8ba16',
    authDomain: 'ipssi-flutter-8ba16.firebaseapp.com',
    storageBucket: 'ipssi-flutter-8ba16.appspot.com',
    measurementId: 'G-FSN3J7XKHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDypkN_zFLepGQ389RjTTt3HjjXcztZIfg',
    appId: '1:282874129758:android:81f5d4970938c19189f3cf',
    messagingSenderId: '282874129758',
    projectId: 'ipssi-flutter-8ba16',
    storageBucket: 'ipssi-flutter-8ba16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqFpCS1TYvH_ty5Kd7BrX-PocLb4AQRds',
    appId: '1:282874129758:ios:bd31ac3fd164670a89f3cf',
    messagingSenderId: '282874129758',
    projectId: 'ipssi-flutter-8ba16',
    storageBucket: 'ipssi-flutter-8ba16.appspot.com',
    iosClientId: '282874129758-j83v8egh8n9la421bdn1a4iotoeg3a4l.apps.googleusercontent.com',
    iosBundleId: 'com.light.ipssisqy2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqFpCS1TYvH_ty5Kd7BrX-PocLb4AQRds',
    appId: '1:282874129758:ios:bd31ac3fd164670a89f3cf',
    messagingSenderId: '282874129758',
    projectId: 'ipssi-flutter-8ba16',
    storageBucket: 'ipssi-flutter-8ba16.appspot.com',
    iosClientId: '282874129758-j83v8egh8n9la421bdn1a4iotoeg3a4l.apps.googleusercontent.com',
    iosBundleId: 'com.light.ipssisqy2023',
  );
}
